#!/usr/bin/env bash
# Install MySQLdb

sudo apt-get install python3-dev -y
sudo apt-get install libmysqlclient-dev -y
sudo apt-get install zlib1g-dev -y
sudo pip3 install mysqlclient
sudo pip3 install SQLAlchemy
